# Blowfish 主题配置

colorScheme = "blowfish"
defaultAppearance = "light"
autoSwitchAppearance = true

enableSearch = true
enableCodeCopy = true
hotlinkFeatureImage = true

[header]
  layout = "fixed"

[footer]
  showMenu = true
  showCopyright = true
  showThemeAttribution = false
  showAppearanceSwitcher = true
  showScrollToTop = true

[homepage]
  layout = "profile"
  showRecent = true
  showRecentItems = 6
  showMoreLink = true
  showMoreLinkDest = "/posts/"
  cardView = true
  cardViewScreenWidth = false

[article]
  showDate = true
  showAuthor = true
  showHero = true
  heroStyle = "background"
  showBreadcrumbs = true
  showReadingTime = true
  showTableOfContents = true
  showTaxonomies = true
  showWordCount = true

[list]
  showHero = true
  heroStyle = "background"
  showCards = true
  groupByYear = true
